name: Production — Deploy ke Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_26BC7AEE1DAE440FBDDDD82A055177E1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B3842740309541589007739ADD6F1986 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABF11EE82A2B483C9024A9BB3470923E }}

      - name: Deploy ke Production
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'crowbarber'
          slot-name: 'Production'
          package: .
